{% set name = "Shapely" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 71f1830bd1aa42d0493c8beb48c2e80712450af43376af4ba3bf40f0d9064120

build:
  number: 0
  # geos currently isn't available on s390x
  skip: True  # [py<37 or s390x]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy 2
    - geos {{ geos }}
    - pip
    - setuptools >=61.0.0
    - wheel
  run:
    - python
    - numpy >=1.14,<3

test:
  requires:
    - pip
    - pytest
  imports:
    - shapely
    - shapely.algorithms
    - shapely.geometry
    - shapely.vectorized
  commands:
    - pip check
    # osx fails if LC_ALL is not Italian or Portuguese
    # see https://github.com/shapely/shapely/blob/2.0.5/shapely/tests/legacy/test_locale.py#L14
    - export LC_ALL=it_IT.UTF-8  # [osx]
    - pytest --pyargs shapely -v

about:
  home: https://github.com/shapely/shapely
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the Cartesian plane
  description: Shapely is a BSD-licensed Python package for manipulation and analysis of planar geometric objects.
  dev_url: https://github.com/shapely/shapely
  doc_url: https://shapely.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - msarahan
