{% set version = "1.6.4" %}

package:
  name: shapely
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Shapely/Shapely-{{ version }}.post1.tar.gz
  sha256: 30df7572d311514802df8dc0e229d1660bc4cbdcf027a8281e79c5fc2fcf02f2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - geos 3.6.2
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - geos 3.6.2

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized
  commands:
    - py.test tests --with-speedups  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
