{% set version = "1.6.2" %}

package:
  name: shapely
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Shapely/Shapely-{{ version }}.tar.gz
  sha256: 0ed0db2ddc10e092de30c2ddae28cc8bd2543601b6af83877b76c3280f2537c6

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - geos 3.5.1
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - geos 3.5.1

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized
  commands:
    - py.test tests --with-speedups  # [linux]
    - conda inspect linkages -p $PREFIX shapely  # [not win]
    - conda inspect objects -p $PREFIX shapely  # [osx]

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
