{% set name = "Shapely" %}
{% set version = "1.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version.split('.post')[0] }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e82b6d60ecfb124120c88fe106a478596bbeab142116d7e7f64a364dac902a92

build:
  number: 0
  # geos currently isn't available on s390x
  skip: True  # [py<36 or s390x]
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29.24,<3
    - geos
    - numpy   1.19  # [py<310]
    - numpy   1.21  # [py>=310]
    - pip
    - setuptools <64
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - shapely
    - shapely.algorithms
    - shapely.examples
    - shapely.geometry
    - shapely.speedups
    - shapely.vectorized
  commands:
    - pip check

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/shapely/shapely/blob/main/LICENSE.txt
  summary: "Python package for manipulation and analysis of geometric objects in the Cartesian plane"

  dev_url: https://github.com/Toblerity/Shapely
  doc_url: https://shapely.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - msarahan
