{% set name = "Shapely" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version.split('.post')[0] }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6250e79ca299222a239ce44df613d228f1216c5cc31351217bf377b03d7be4e0

build:
  number: 0
  # geos currently isn't available on s390x
  skip: True  # [py<37 or s390x]
  skip: True  # [win and vc<14]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython 0.29.34
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - shapely
  commands:
    - pip check
    - pytest --pyargs shapely.tests

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Python package for manipulation and analysis of geometric objects in the Cartesian plane"
  description: Shapely is a BSD-licensed Python package for manipulation and analysis of planar geometric objects
  dev_url: https://github.com/Toblerity/Shapely
  doc_url: https://shapely.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
    - xylar
    - msarahan
