{% set version = "1.6.2" %}

package:
  name: shapely
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Shapely/Shapely-{{ version }}.tar.gz
  sha256: 0ed0db2ddc10e092de30c2ddae28cc8bd2543601b6af83877b76c3280f2537c6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - geos
    - msinttypes  # [win and vc<14]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized
  commands:
    - py.test tests --with-speedups  # [linux]
    - conda inspect linkages -p $PREFIX shapely  # [not win]
    - conda inspect objects -p $PREFIX shapely  # [osx]

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
    - msarahan
