{% set version = "1.5.17" %}

package:
  name: shapely
  version: {{ version }}

source:
  fn: Shapely-{{ version }}.tar.gz
  url: https://github.com/Toblerity/Shapely/archive/{{ version }}.post1.tar.gz
  sha256: 1c0ba006875edef296aeed4f1cdadafa8f0c6c3bf5eae8aeae0f7e394ed62578
  patches:
    - geos_c.patch

build:
  number: 4

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - geos 3.5.1
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - geos 3.5.1

test:
  requires:
    - pytest
  imports:
    - shapely
    - shapely.speedups._speedups
    - shapely.vectorized._vectorized
  commands:
    - cp -r $SRC_DIR/tests /tmp && cd /tmp && py.test --with-speedups  # [linux]
    - conda inspect linkages -p $PREFIX shapely  # [not win]
    - conda inspect objects -p $PREFIX shapely  # [osx]

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - phobson
