travis:
  secure:
    BINSTAR_TOKEN: FCkrRI0VeulchzPWuphSI9DOVzjVQf4YPQpBQ/BUPUJZe1HYvISxmrthkgo1sJE5crSGctfRtFHodV7cBQU/D371ph8+TiAkH6JSDtHwb+YBaRLz+e4y6eN5Q9rXsH2y46sOIQHD0fAkpuCKtmcKK03gVesY/YTujVhKnO1NJn59sN6DqIxboiXQQnl+Io/zTroSuQPgdQSopwJBWn3GfzlNsIP2zDktuw7PneocE6qbqmsN/VE0ENTDjqaTiWmUijcvPyLpp/qlzj4rs9GiQfdsbUlFKP19LmoUHzWsc5JTPgpphRBvf0UpuKkEv3NRqyQV7OKpa5ec6SuT20OM+2Exfa4uT5w4LWx75BJab3bpD2A/3P6V5WkVFsH7OZ/NwjAqxqustnYO410LO47wWAlWlDCKw4R/kiS3hSmcT0+afquJWNFKlUHFmugcjVahkfr+tswJ/JwtlROWtFxyxAOza2i/96/LSj2MlpgcY6YNVCXiiVZMo3TOe23CCkqLvCKmmyGJTAAzW0Tdt0IL9LDw1iPlRYx15ITLwsRw5C1M4Av0Obv5BUIdl/shh4p+NMspg10jY+Z2I2fpYwkkdz1BZb6eHKwP9RWNnHFbP9+Gr7OrAX7+HWFZTmdqVnwsHVxujccn+5yQ3kWT2YiKpt1RWL6C7r6QfUfKIn8W+sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
