travis:
  secure:
    BINSTAR_TOKEN: cqSdA1zylBY2ufD69lmXxMPSMVJb29jo6pEGod/j+LFudyDoF9HvqSSE7J7iRcJfQUuHLriXmwB1zVaf4mCG3IGKZzK8x+7mzCpMASEq3x2iCN8Dp2HOmpLhZDhCSgJBk/H8J0Xde2tOB3JH9dFtGl2S+ChTpmh6uWSiR7V99Z3B+ylDWXIVm7lW8VK/f3F2WRwiy28xgjjUL1m9DkM5HTe43MF0i393PJZbff/WF73WAZuj1Gd1KMxPFPk0l3g0cSjz8YAw3pnOe7IS3pPX6Mx6UmnSx6OPHCbqRSdaRj1mq3kIU7k1ydNnbsL9ApQAu+GxwbvJAiOTqamrs364QXaJMy5bvTKA2OHJ+3MOdcfdC5mjfXe0qwyRbsqiLoZ9u/2VIhaw5nzcvg79VhEE0OsE7SNSilxwXnezKiu7/FZY+A7oTOOhM+9KdsexBNqDI/v/fEk1zupRg2FIwsIx2jrD1nhSIgsJzd6k/3wQW/qtz6JicFERnXPbhdoPWMKP2M+xueDxao2a8yKMfFbhR5KmJg/K5ehFuhuAd2YMfVJ3W9BE+1s+CYTGIZRFK+bmC3ONujqth6vSOuxljNnGEFThfPrN4IQxNPCC67f4Ce2u1xv4aQNO0izydg2iuB9rzPABqLrv5LdNx6P3RwD8E7eGlnsXhHuFLXqBawqeAzA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
